services:
  - type: web
    name: automatisation-cma
    env: python
    region: frankfurt
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
