services:
  - type: web
    name: automatisation-cma
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
